[package]
name = "with-async-context"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project = { version = "1.1.10" }
tokio = { version = "1.36.0", features = ["rt", "macros", "time"] }
log = "0.4.20"

[dev-dependencies]
futures = "0.3.26"
